package MainPage;

import com.mycompany.evalsystem.EvalSystem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class studentPanel extends javax.swing.JPanel {

Connection conn;
PreparedStatement pst;
ResultSet rs;
    
public studentPanel() {
        initComponents();
        
        conn = EvalSystem.conn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        question1Ans = new javax.swing.JComboBox<>();
        question1 = new javax.swing.JLabel();
        question3Ans = new javax.swing.JComboBox<>();
        question2 = new javax.swing.JLabel();
        question2Ans = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        question4Ans = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        question5Ans = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        question6Ans = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        question7Ans = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        question8Ans = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        question9Ans = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        question10Ans = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        question11Ans = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        question12Ans = new javax.swing.JComboBox<>();
        question13Ans = new javax.swing.JComboBox<>();
        question4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        question14Ans = new javax.swing.JComboBox<>();
        question15Ans = new javax.swing.JComboBox<>();
        question6 = new javax.swing.JLabel();
        question7 = new javax.swing.JLabel();
        question16Ans = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        question17Ans = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        question18Ans = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        question19Ans = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        question20Ans = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        question21Ans = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        question8 = new javax.swing.JLabel();
        question22Ans = new javax.swing.JComboBox<>();
        question9 = new javax.swing.JLabel();
        question23Ans = new javax.swing.JComboBox<>();
        question10 = new javax.swing.JLabel();
        question24Ans = new javax.swing.JComboBox<>();
        question11 = new javax.swing.JLabel();
        question25Ans = new javax.swing.JComboBox<>();
        question12 = new javax.swing.JLabel();
        question26Ans = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        teacherComboBox = new javax.swing.JComboBox<>();
        studentNumberField = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        jLabel14.setText("jLabel14");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CCST EVALUATION SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(176, 176, 176))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Kindly rate your teacher's performance in each <br> area based on the following ratings: </html>");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("5");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 51));
        jLabel4.setText("4");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("3");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 153, 0));
        jLabel6.setText("2");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("1");

        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("EXCELLENT");

        jLabel10.setForeground(new java.awt.Color(0, 204, 51));
        jLabel10.setText("VERY GOOD");

        jLabel11.setForeground(new java.awt.Color(204, 204, 0));
        jLabel11.setText("GOOD");

        jLabel12.setForeground(new java.awt.Color(204, 153, 0));
        jLabel12.setText("NEEDS IMPROVEMENT");

        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("POOR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 160, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 204));
        jLabel15.setText("A.");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 204));
        jLabel16.setText("Teaching Performance");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 181, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 153));
        jLabel17.setText("<html>3. Is able to adjust himself/herself to learning capacities/ comprehension of his students</html>");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 381, 71));

        question1Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question1Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 162, -1));

        question1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question1.setForeground(new java.awt.Color(0, 102, 153));
        question1.setText("<html>1. Make systematic and thorough presentation of the subject matter</html>");
        add(question1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 237, 381, 71));

        question3Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question3Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 160, -1));

        question2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question2.setForeground(new java.awt.Color(0, 102, 153));
        question2.setText("<html>2. Relates subject matter to other fields, to actual life in and out of class situation</html>");
        add(question2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 381, 71));

        question2Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question2Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 160, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 153));
        jLabel18.setText("<html>4. Welcomes question, stimulates interest, thinking and discussions</html>");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 381, 71));

        question4Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question4Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 690, 160, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 153));
        jLabel19.setText("<html>5. Updated with current issues regarding the subject</html>");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 750, 381, 71));

        question5Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question5Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 830, 160, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 153));
        jLabel20.setText("<html>6. If lesson is not understood, he takes time to explain so there will be complete</html>");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 890, 381, 71));

        question6Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question6Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 970, 160, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 153));
        jLabel21.setText("<html>7. Creates teaching strategies that allow students to practice using concepts they need to\nunderstand (interactive discussion)</html>");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1020, 470, 71));

        question7Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question7Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1100, 160, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 153));
        jLabel22.setText("<html>8. Maintains a receptive and disciplined learning atmosphere (classroom discipline)</html>");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1150, 381, 71));

        question8Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question8Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1230, 160, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 153));
        jLabel23.setText("<html>9. Shows mastery of the subject matter</html>");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1290, 381, 71));

        question9Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question9Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1370, 160, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 153));
        jLabel24.setText("<html>10. Teacher communicates clearly and correctly</html>");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1420, 381, 71));

        question10Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question10Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1500, 160, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 153));
        jLabel25.setText("<html>11. Teaching materials/presentations are appropriate</html>");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1560, 381, 71));

        question11Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question11Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1640, 160, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 204));
        jLabel26.setText("B.");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 204));
        jLabel27.setText("Professionalism");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        question3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question3.setForeground(new java.awt.Color(0, 102, 153));
        question3.setText("<html>12. The teacher is always present</html>");
        add(question3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 620, 381, 71));

        question12Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question12Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 690, 162, -1));

        question13Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question13Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 800, 162, -1));

        question4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question4.setForeground(new java.awt.Color(0, 102, 153));
        question4.setText("<html>13. The teacher comes to class on time</html>");
        add(question4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 730, 381, 71));

        question5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question5.setForeground(new java.awt.Color(0, 102, 153));
        question5.setText("<html>14. The teacher dismisses the class on time</html>");
        add(question5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 850, 381, 71));

        question14Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question14Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 920, 162, -1));

        question15Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question15Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1050, 162, -1));

        question6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question6.setForeground(new java.awt.Color(0, 102, 153));
        question6.setText("<html>15. The teacher maximizes the use of time in discussing necessary and related topics</html>");
        add(question6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 980, 381, 71));

        question7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question7.setForeground(new java.awt.Color(0, 102, 153));
        question7.setText("<html>16. Open to suggestion and criticism that promotes healthy exchange and/ or confrontation</html>");
        add(question7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1090, 381, 71));

        question16Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question16Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1160, 162, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 204));
        jLabel28.setText("C.");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1740, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 204));
        jLabel29.setText("Compliance with Rules and Regulations");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1760, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 153));
        jLabel30.setText("<html>17. Teacher checks attendance regularly</html>");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1810, 381, 71));

        question17Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question17Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1890, 160, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 153));
        jLabel31.setText("<html>18. Teacher follows syllabus/outline in his/her lesson</html>");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1940, 381, 71));

        question18Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question18Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2020, 160, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 153));
        jLabel32.setText("<html>19. Teacher returns test paper/quizzes</html>");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2070, 381, 71));

        question19Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question19Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2150, 160, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 153));
        jLabel33.setText("<html>20. Teacher always check compliance of students with proper/complete uniform</html>");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2200, 381, 71));

        question20Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question20Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2280, 160, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 153));
        jLabel34.setText("<html>21. Teacher makes himself/herself available for consultations.</html>");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 2340, 381, 71));

        question21Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question21Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 2420, 160, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 204));
        jLabel35.setText("Personal Qualification");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 1239, -1, 40));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 153, 204));
        jLabel36.setText("D.");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 1230, -1, -1));

        question8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question8.setForeground(new java.awt.Color(0, 102, 153));
        question8.setText("<html>22. Possess a pleasant disposition/personality</html>");
        add(question8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1290, 381, 71));

        question22Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question22Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1360, 162, -1));

        question9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question9.setForeground(new java.awt.Color(0, 102, 153));
        question9.setText("<html>23. Courteous and tactful</html>");
        add(question9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1400, 381, 71));

        question23Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question23Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1470, 162, -1));

        question10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question10.setForeground(new java.awt.Color(0, 102, 153));
        question10.setText("<html>24. Dress neatly and appropriately</html>");
        add(question10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1520, 381, 71));

        question24Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question24Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1590, 162, -1));

        question11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question11.setForeground(new java.awt.Color(0, 102, 153));
        question11.setText("<html>25. Possesses a well-modulated voice</html>");
        add(question11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1640, 381, 71));

        question25Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question25Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1710, 162, -1));

        question12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        question12.setForeground(new java.awt.Color(0, 102, 153));
        question12.setText("<html>26. Possesses a good sense of humor</html>");
        add(question12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1760, 381, 71));

        question26Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 - Excellent", "4- Very Good", "3 - Good", "2- Needs improvement", "1- Poor" }));
        add(question26Ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 1830, 162, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 1940, 200, 50));

        teacherComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher 1", "Teacher 2", "Teacher 3" }));
        add(teacherComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 160, -1));

        studentNumberField.setText("Stufdent Number");
        add(studentNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String teacherToEvaluate = (String) teacherComboBox.getSelectedItem();
        String studentNum = studentNumberField.getText();
        // A
        String question1 = (String) question1Ans.getSelectedItem();
        String question2 = (String) question2Ans.getSelectedItem();
        String question3 = (String) question3Ans.getSelectedItem();
        String question4 = (String) question4Ans.getSelectedItem();
        String question5 = (String) question5Ans.getSelectedItem();
        String question6 = (String) question6Ans.getSelectedItem();
        String question7 = (String) question7Ans.getSelectedItem();
        String question8 = (String) question8Ans.getSelectedItem();
        String question9 = (String) question9Ans.getSelectedItem();
        String question10 = (String) question10Ans.getSelectedItem();
        String question11 = (String) question11Ans.getSelectedItem();
        
        //B 
        String question12 = (String) question12Ans.getSelectedItem();
        String question13 = (String) question13Ans.getSelectedItem();
        String question14 = (String) question14Ans.getSelectedItem();
        String question15 = (String) question15Ans.getSelectedItem();
        String question16 = (String) question16Ans.getSelectedItem();
        
        //C
        String question17 = (String) question17Ans.getSelectedItem();
        String question18 = (String) question18Ans.getSelectedItem();
        String question19 = (String) question19Ans.getSelectedItem();
        String question20 = (String) question20Ans.getSelectedItem();
        String question21 = (String) question21Ans.getSelectedItem();
        
        //D
        String question22 = (String) question22Ans.getSelectedItem();
        String question23 = (String) question23Ans.getSelectedItem();
        String question24 = (String) question24Ans.getSelectedItem();
        String question25 = (String) question25Ans.getSelectedItem();
        String question26 = (String) question26Ans.getSelectedItem();

        
        try {
            String entryQuery = "INSERT INTO Student_Entries (Student_Number, Teacher_to_Evaluate, q1, q2, q3, q4, q5, q6, q7, q8,"
            + " q9, q10, q11, q12, q13, q14, q15, q16, q17, q18, q19, q20, q21, q22, q23, q24, q25, q26) VALUES (?, ?, ?, ?, ?,"
            + " ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(entryQuery);
            pst.setString(1, studentNum);
            pst.setString(2, teacherToEvaluate);
            pst.setString(3, question1);
            pst.setString(4, question2);
            pst.setString(5, question3);
            pst.setString(6, question4);
            pst.setString(7, question5);
            pst.setString(8, question6);
            pst.setString(9, question7);
            pst.setString(10, question8);
            pst.setString(11, question9);
            pst.setString(12, question10);
            pst.setString(13, question11);
            pst.setString(14, question12);
            pst.setString(15, question13);
            pst.setString(16, question14);
            pst.setString(17, question15);
            pst.setString(18, question16);
            pst.setString(19, question17);
            pst.setString(20, question18);
            pst.setString(21, question19);
            pst.setString(22, question20);
            pst.setString(23,question21);
            pst.setString(24, question22);
            pst.setString(25, question23);
            pst.setString(26, question24);
            pst.setString(27, question25);
            pst.setString(28, question26);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Submission Successful");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question10;
    private javax.swing.JComboBox<String> question10Ans;
    private javax.swing.JLabel question11;
    private javax.swing.JComboBox<String> question11Ans;
    private javax.swing.JLabel question12;
    private javax.swing.JComboBox<String> question12Ans;
    private javax.swing.JComboBox<String> question13Ans;
    private javax.swing.JComboBox<String> question14Ans;
    private javax.swing.JComboBox<String> question15Ans;
    private javax.swing.JComboBox<String> question16Ans;
    private javax.swing.JComboBox<String> question17Ans;
    private javax.swing.JComboBox<String> question18Ans;
    private javax.swing.JComboBox<String> question19Ans;
    private javax.swing.JComboBox<String> question1Ans;
    private javax.swing.JLabel question2;
    private javax.swing.JComboBox<String> question20Ans;
    private javax.swing.JComboBox<String> question21Ans;
    private javax.swing.JComboBox<String> question22Ans;
    private javax.swing.JComboBox<String> question23Ans;
    private javax.swing.JComboBox<String> question24Ans;
    private javax.swing.JComboBox<String> question25Ans;
    private javax.swing.JComboBox<String> question26Ans;
    private javax.swing.JComboBox<String> question2Ans;
    private javax.swing.JLabel question3;
    private javax.swing.JComboBox<String> question3Ans;
    private javax.swing.JLabel question4;
    private javax.swing.JComboBox<String> question4Ans;
    private javax.swing.JLabel question5;
    private javax.swing.JComboBox<String> question5Ans;
    private javax.swing.JLabel question6;
    private javax.swing.JComboBox<String> question6Ans;
    private javax.swing.JLabel question7;
    private javax.swing.JComboBox<String> question7Ans;
    private javax.swing.JLabel question8;
    private javax.swing.JComboBox<String> question8Ans;
    private javax.swing.JLabel question9;
    private javax.swing.JComboBox<String> question9Ans;
    private javax.swing.JTextField studentNumberField;
    private javax.swing.JComboBox<String> teacherComboBox;
    // End of variables declaration//GEN-END:variables
}
